module.exports = {
  BOOKS_DB: 'in/google-books/books_with_mid.db',
  AUTHORS: 'out/db/authors.json',
  BOOKS_JSON: 'out/books',
  GEONAMES_DB: './out/baseIslands/geonames.db',
  SHORELINES: 'out/baseIslands/gshhs/shorelines.geo.json',
  BASE_ISLANDS: 'out/baseIslands/baseIslands.geo.json',
  BASE_ISLANDS_LOWDEF: 'out/baseIslands/baseIslands_lowdef.geo.json',
  BASE_ISLANDS_LOWDEF_MRCT: 'out/baseIslands/baseIslands_lowdef_mrct.geo.json',
  GEONAMES_POP_PLACES: 'out/baseIslands/populated_places.csv',
  CITIES_REAL: 'out/baseIslands/cities.geo.json',
  CITIES_STATS: 'out/baseIslands/cities_stats.json',
  UMAP_CAT: 'in/umap/cat',
  HGT_DATA: 'in/hgt',
  UMAP_CAT_STATS: 'out/umap/umap_cat_stats.json',
  UMAP_GEO: 'out/umap/umap.geo.json',
  CLUSTERS: 'out/layout/clusters.geo.json',
  BASE_ISLANDS_META: 'out/layout/baseIslandsMeta.json',
  ISLANDS: 'out/layout/islands.geo.json',
  ISLANDS_LOWDEF: 'out/layout/islands_lowdef.geo.json',
  ISLANDS_META: 'out/layout/islands.meta.json',
  BOOKS_POINTS: 'out/layout/books_points.geo.json',
  TERRITORY_LABELS: 'out/layout/territory_labels.geo.json',
  TERRITORY_FRONTIERS: 'out/layout/territory_frontiers.geo.json',
  ISLANDS_TILES: 'tiles/islands',
  POINTS_TILES: 'tiles/points',
  HEIGHT_TILES: 'tiles/height',
  HEIGHT_TILE_SIZE: 256,
  HEIGHT_EMPTY_TILE: 'scripts/tiles/height/blank.png',
  TEST_BBOX: {
    minX: -10,
    minY: -10,
    maxX: 0,
    maxY: 0
  },
  BBOX_CHUNKS:[
    [-180, -80, -10, 0],
    [-10 , -80, 0  , 0],
    [-180, 0  , 0  , 80],
    [0   , 0  , 180, 80],
    [0   , -80, 10, 0],
    [10  , -80, 20, 0],
    [20  , -80, 180, 0]
  ],
  MAX_BASE_ISLAND_SCALE_UP: 2
}
